version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: test-task-grafana
    ports:
      - 3000:3000
    environment:
     - GF_INSTALL_PLUGINS=vertamedia-clickhouse-datasource
     - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
     - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
    volumes:
     - ./provisioning:/etc/grafana/provisioning
    depends_on:
      - clickhouse

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: test-task-clickhouse
    ports:
      - 8123:8123
      - 9000:9000
    environment:
     - CLICKHOUSE_DB=${CLICKHOUSE_DB:-db_name}
     - CLICKHOUSE_USER=${CLICKHOUSE_USER:-admin}
     - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-admin}
    volumes:
      - clickhouse-volume:/var/lib/clickhouse

  tabix:
    image: spoonest/clickhouse-tabix-web-client
    container_name: test-task-clickhouse-ui
    ports:
      - 8080:80
    environment:
     - CH_NAME=dev
     - CH_HOST=http://127.0.0.1:8123
     - CH_LOGIN=${CLICKHOUSE_USER:-admin}
     - CH_PASSWORD=${CLICKHOUSE_PASSWORD:-admin}

volumes:
  clickhouse-volume:
