version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: test-task-grafana
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
    volumes:
     - ./provisioning:/etc/grafana/provisioning
     - ./provisioning/dashboards/:/var/lib/grafana/dashboards/
    depends_on:
      - clickhouse
    networks:
      - docker-network

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: test-task-clickhouse
    restart: always
    ports:
      - 8123:8123
      - 9000:9000
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB:-db_name}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-admin}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-admin}
    volumes:
      - clickhouse-volume:/var/lib/clickhouse
    networks:
      - docker-network

  update_prices:
    build: .
    container_name: test-task-update_prices
    restart: always
    volumes:
      - .:/code
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB:-db_name}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-admin}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-admin}
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
    depends_on:
      - clickhouse
    networks:
      - docker-network
    command: sh -c "sleep 10 && python ./update_prices/main.py"

volumes:
  clickhouse-volume:

networks:
  docker-network:
    driver: bridge
